name: Release-plz

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  release:
    name: Release-plz release
    if: ${{ github.repository_owner == 'ratatui' }}
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      id-token: write
      pull-requests: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@fa04a1451ff1842e2626ccb99004d0195b455a88 # master
        with:
          toolchain: stable
      - name: Run release-plz (release)
        uses: release-plz/action@2eb1d8bcb770b4c48ccfaad919734b38b51958c9 # v0.5.131
        with:
          command: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release_pr:
    name: Release-plz PR
    if: ${{ github.repository_owner == 'ratatui' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    concurrency:
      group: release-plz-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@fa04a1451ff1842e2626ccb99004d0195b455a88 # master
        with:
          toolchain: stable
      - name: Install release-plz
        uses: taiki-e/install-action@43aecc8d72668fbcfe75c31400bc4f890f1c5853 # v2.83.2
        with:
          tool: release-plz@0.3.150,cargo-semver-checks@0.45
      - name: Run release-plz (release-pr)
        run: >
          release-plz release-pr
          --repo-url "https://github.com/${{ github.repository }}"
        env:
          GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
